### ISSUE TITLE
Job pending State

### ISSUE THREAD

**Issue by 67726e** [wildhart/meteor.jobs#11]
I'm having trouble understanding how and when a job is run.

```
// ./job/register.js
Jobs.register({
  performAction: function() { /**/ },
});

Jobs.start();

// ./main.js
import './job/register';

Meteor.methods({
  performAction() {
    Jobs.run('performAction');
  },
});

// Make a `Meteor.call('performAction')` client-side...
```

This is being run on a fresh system, no others jobs to hog the queue. When running the above, I'm seeing a 5+ minute wait before the `performAction` job is invoked. I would expect this to be nearly immediately invoked. Is this level of delay expected?

**Comment by 67726e** [comment]
The 5 minute delay appears to be consistent, having run several tests of this in a row:

```
=> App running at: http://localhost:3000/
I20210326-09:16:09.829(-4)? Jobs startup FM3YL5TbTTZ8DAgdw {"_id":"dominatorId","serverId":"Qi52NwkTfeJ2wEz6X","pausedJobs":[],"date":"2021-03-26T13:14:51.819Z"} isOld=false
I20210326-09:16:09.829(-4)? Jobs dominator.observer {
I20210326-09:16:09.830(-4)?   _id: 'dominatorId',
I20210326-09:16:09.830(-4)?   serverId: 'Qi52NwkTfeJ2wEz6X',
I20210326-09:16:09.830(-4)?   pausedJobs: [],
I20210326-09:16:09.833(-4)?   date: 2021-03-26T13:14:51.819Z
I20210326-09:16:09.833(-4)? }







I20210326-09:16:30.247(-4)? Jobs Jobs.run sendSigningRequest { documentID: 'yczW5DavZgqv7rGSe', requestID: '7hy7XXRoMedHKgsiY' }
I20210326-09:21:09.838(-4)? Jobs takeControl lastPingIsOld {"_id":"dominatorId","serverId":"Qi52NwkTfeJ2wEz6X","pausedJobs":[],"date":"2021-03-26T13:14:51.819Z"}
I20210326-09:21:09.838(-4)? Jobs ping 2021-03-26T13:21:09.835Z paused: []
I20210326-09:21:09.839(-4)? Jobs queue.start paused: []
I20210326-09:21:09.843(-4)? Jobs queue.observer added {
I20210326-09:21:09.843(-4)?   due: 2021-03-26T13:16:30.247Z,
I20210326-09:21:09.843(-4)?   name: 'sendSigningRequest',
I20210326-09:21:09.844(-4)?   _id: 'ebtsdNP52m7DvHqsj'
I20210326-09:21:09.844(-4)? } -0.08h
I20210326-09:21:09.844(-4)? Jobs dominator.observer {
I20210326-09:21:09.845(-4)?   serverId: 'FM3YL5TbTTZ8DAgdw',
I20210326-09:21:09.845(-4)?   pausedJobs: [],
I20210326-09:21:09.845(-4)?   date: 2021-03-26T13:21:09.835Z,
I20210326-09:21:09.846(-4)?   _id: 'dominatorId'
I20210326-09:21:09.849(-4)? }
I20210326-09:21:09.849(-4)? Jobs executeJobs paused: []
I20210326-09:21:09.850(-4)? Jobs queue.observer stop null null
I20210326-09:21:09.850(-4)? Jobs   sendSigningRequest
I20210326-09:21:09.850(-4)? ===== sendSigningRequest
I20210326-09:21:09.850(-4)? Signing Request: http://local-signer.simplesigner.com/signer/7hy7XXRoMedHKgsiY
I20210326-09:21:09.850(-4)? ===== sendSigningRequest undefined
I20210326-09:21:09.851(-4)? Jobs setJobState ebtsdNP52m7DvHqsj success 1
I20210326-09:21:09.851(-4)? Jobs     Done job sendSigningRequest result=success
I20210326-09:21:09.851(-4)? Jobs queue.start paused: []
```

**Comment by wildhart** [comment]
This 5 minute delay is a consequence of the job queue thinking it might be running in a multi-server environment.  In a multi-server environment, when a server starts the job package cannot immediately start running jobs because the package might also be running on another server which is in control of the job queue.  The new server has to wait to make sure that another server is not running.  This is the `Jobs take Control last PingIsOld` line in the logs, exactly 5 minutes after the server starts.

See the [Jobs.Configure](https://github.com/wildhart/meteor.jobs#jobsconfigure) section of the docs, specifically:
```
// (milliseconds) specify how long the server could be inactive before another server takes on the
// master role (default = 5min)
maxWait: Number,

// determine how to set the serverId - see below. (default = random string)
setServerId: String || Function,
```
If you have a multi-server environment and want to reduce this delay, change `maxWait` to a lower number.  If you are running in a single server environment set `setServerId` to a constant string, e.g. `setServerId: 'myOnlyServer'`;

Using `setServerId` when the package starts it will see that the `serverId` in the last ping is that same as it's own `serverId`, so it will know that it should re-take control immediately.  The first time you do this there will still be a 5 minute delay because to start with the `serverId` in the last ping is the old random id.

**Comment by 67726e** [comment]
Thanks for the assistance!

After setting the `setServerId` function and removing the old server registry `db.jobs_dominator_3.remove({})` jobs began to run immediately.

**Comment by yuwiggin** [comment]
My jobs status were "pending" and could Not run on time. Any suggestion？

console message::
```
=> App running at: http://localhost:3000/
I20230305-14:10:50.979(8)? Jobs startup myOnlyServer {"_id":"dominatorId","pausedJobs":[]} isOld=undefined
I20230305-14:10:50.979(8)? Jobs takeControl no ping
I20230305-14:10:50.981(8)? Jobs ping 2023-03-05T06:10:50.979Z paused: []
I20230305-14:10:50.981(8)? Jobs queue.start paused: []
I20230305-14:10:50.986(8)? Jobs dominator.observer {
I20230305-14:10:50.987(8)?   pausedJobs: [],
I20230305-14:10:50.987(8)?   _id: 'dominatorId',
I20230305-14:10:50.987(8)?   serverId: 'myOnlyServer',
I20230305-14:10:50.987(8)?   date: 2023-03-05T06:10:50.979Z
I20230305-14:10:50.987(8)? }
I20230305-14:10:50.987(8)? Jobs queue.observer added {
I20230305-14:10:50.987(8)?   due: 2023-04-11T21:42:00.000Z,
I20230305-14:10:50.987(8)?   name: 'publishWeekly',
I20230305-14:10:50.987(8)?   _id: 'DgMv4uAbXbL7DPANh'
I20230305-14:10:50.988(8)? } 903.52h
...
I20230305-14:17:31.409(8)? Jobs ping 2023-03-05T06:17:31.403Z paused: []
I20230305-14:17:31.409(8)? Jobs dominator.observer {
I20230305-14:17:31.409(8)?   pausedJobs: [],
I20230305-14:17:31.409(8)?   _id: 'dominatorId',
I20230305-14:17:31.410(8)?   serverId: 'myOnlyServer',
I20230305-14:17:31.410(8)?   date: 2023-03-05T06:17:31.403Z
I20230305-14:17:31.410(8)? }
I20230305-14:18:11.477(8)? Jobs ping 2023-03-05T06:18:11.472Z paused: []
I20230305-14:18:11.478(8)? Jobs dominator.observer {
I20230305-14:18:11.478(8)?   pausedJobs: [],
I20230305-14:18:11.478(8)?   _id: 'dominatorId',
I20230305-14:18:11.478(8)?   serverId: 'myOnlyServer',
I20230305-14:18:11.478(8)?   date: 2023-03-05T06:18:11.472Z
I20230305-14:18:11.478(8)? }

```

MongoDB data:
```
id" : "dominatorId", "serverId" : "myOnlyServer", "pausedJobs" : [ ], "date" : ISODate("2023-03-05T06:10:50.979Z") }
db.jobs_data.find()
{ "_id" : "DgMv4uAbXbL7DPANh", "name" : "publishWeekly", "arguments" : [ ], "state" : "pending", "due" : ISODate("2023-04-11T21:42:00Z"), "priority" : 0, "created" : ISODate("2023-03-05T06:10:49.939Z") }
```

Env:
meteor: 2.5.8
mongo: 4.2.17

**Comment by chrismorison-wt** [comment]
@yuwiggin the job's due date is not until 11th April: `"due" : ISODate("2023-04-11T21:42:00Z")`.  Have you tried setting a due date for a few seconds/minutes time, or in the past?  Then the job should run.

See the docs for [Jobs.run()](https://github.com/wildhart/meteor.jobs#jobsrun)

**Comment by yuwiggin** [comment]
Thank you very much for your comment.  How to config the `due` ? I want to do some repeating jobs. According to document, 
```
Jobs.register({
	processMonthlyPayments() {
		this.reschedule({in: {months: 1}});
		processPayments();
	},
});

Jobs.run('processMonthlyPayments', {singular: true});
```
How to define  the function `processPayments` and where is it put in, Meteor.methods() or else?

**Comment by chrismorison-wt** [comment]
In your example,`processPayments()` would be just a normal javascript method, not a Meteor.method.  You can define it right after the `Jobs.regsiter()` block if you want, or import it from another file.  Or you can put the code directly in the `processMonthlyPayments` job definition.

**Comment by yuwiggin** [comment]
Thank you again.  Another question, How to config the `due` ? It always is set in one month that is not my expection.

**Comment by chrismorison-wt** [comment]
See the docs for [Jobs.run()](https://github.com/wildhart/meteor.jobs#jobsrun) and add an `in` or `on` or `date` parameter, e.g.

`Jobs.run('processMonthlyPayments', {singular: true, in: {minutes: 1}});`

Or if you want the job to run every month on the first day of the month:

```
Jobs.register({
	processMonthlyPayments() {
		this.reschedule({in: {months: 1}});
		processPayments();
	},
});

const today = new Date();
const firstOfNextMonth = new Date(today.getFullYear(), today.getMonth() + 1, 1);

Jobs.run('processMonthlyPayments', {singular: true, date: firstOfNextMonth});
```

However, note that your server is probably running in UTC, so you might need to take timezones into account if you want your job to run at an exact time each month in your own timezone.

**Comment by yuwiggin** [comment]
Thank you for your answer. I tried to set my jobs to run on a specific time, but failed. When the `due` field of  ` jobs_data`  is set to new Date() manually, the jobs ran right away. But this trick is not the solution what I needed. Could the jobs can run automatically on the specific time? How to config it?

**Comment by chrismorison-wt** [comment]
In your example, what is `nextTime`?  Have you tried passing the `date:` option to `Jobs.run()` instead of the `on:` option?
