### ISSUE TITLE
Missing `Mongo` Import in Type Definition

### ISSUE THREAD

**Issue by 67726e** [wildhart/meteor.jobs#20]
Howdy,

I recently copied over your type definition file into my Meteor project and received an error:

```
Cannot find namespace 'Mongo'.ts(2503)
```

See Line: https://github.com/wildhart/meteor.jobs/blob/350c07c6053bc8a742d243fbd061a7791a5574b4/wildhart-jobs.d.ts#L52

I was able to fix it locally with 

```
declare module 'meteor/wildhart:jobs' {
    import type { Mongo } from 'meteor/mongo';
```

However, I wasn't sure if this file was hand-written or generated so didn't create a PR.

**Comment by 67726e** [comment]
Found another mismatch between the stated README and the Typescript / definition file.

The `.start()` function takes either `void` or `string` or `string[]` per the README, but the `job.ts` and `wildhart-jobs.d.ts` define only `string | string[]`. The code does work as described, it gracefully handles a lack of input, but the definition doesn't allow for it and errors on:

```
Expected 1 arguments, but got 0.ts(2554)
```

See Line: https://github.com/wildhart/meteor.jobs/blob/350c07c6053bc8a742d243fbd061a7791a5574b4/wildhart-jobs.d.ts#L66
See Line: https://github.com/wildhart/meteor.jobs/blob/350c07c6053bc8a742d243fbd061a7791a5574b4/jobs.ts#L67

I was able to fix it locally with:

```
        function start(jobNames?: string | string[]): void;
```

Note the `jobNames?` changed from the original `jobNames`.

**Comment by 67726e** [comment]
If you'd like, I can take a crack at shoring up the `job.ts` and `wildhart-jobs.d.ts` vis a vis the README. I'm just not sure at this point if you're creating this via generation or hand-writing it.

**Comment by chrismorison-wt** [comment]
Hi @67726e.  Thanks for taking the time to report these problems, and for using this package!

The type definition files are hand-written, so if you've got fixed versions feel free to post them here or submit a PR. I should be able to merge them and publish an updated package pretty quickly.

**Comment by 67726e** [comment]
Hey @chrismorison-wt  - I apologize for my lack of response. 

I'm going to take a crack at fixing the delta between the code, the type definition, and the README here this weekend.

**Comment by 67726e** [comment]
Alright, my original idea of just updating the types went a little bit beyond. Using the TypeScript compiler, `tsc`, we can emit declarations directly from the `job.ts` file.

```
npx tsc jobs.ts --skipLibCheck --declaration --emitDeclarationOnly
```

Figured this would make for a good first-stage.


```
import { Mongo } from 'meteor/mongo';
/********************************* Dominator *********************/
declare namespace Dominator {
    interface Document {
        _id?: string;
        serverId?: string;
        pausedJobs: string[];
        date?: Date;
    }
    export const collection: Mongo.Collection<Document, Document>;
    export let lastPing: Readonly<Document>;
    export function init(): void;
    export function start(jobNames: string[] | string): void;
    export function stop(jobNames: string[] | string): void;
    export {};
}
/********************************* Public API *********************/
export declare namespace Jobs {
    interface Config {
        startupDelay: number;
        maxWait: number;
        log: typeof console.log | boolean;
        autoStart: boolean;
        setServerId?: string | Function;
        defaultCompletion?: 'success' | 'remove';
    }
    interface JobConfig {
        in: any;
        on: any;
        priority: number;
        date: Date;
        state: string;
        awaitAsync: boolean;
        unique: boolean;
        singular: boolean;
        callback?: Function;
    }
    type JobStatus = "pending" | "success" | "failure" | "executing";
    interface JobDocument {
        _id: string;
        name: string;
        state: JobStatus;
        arguments: any[];
        due: Date;
        priority: number;
        created: Date;
        awaitAsync?: boolean;
    }
    interface JobThisType {
        document: JobDocument;
        replicate(config: Partial<JobConfig>): string | null;
        reschedule(config: Partial<JobConfig>): void;
        remove(): boolean;
        success(): void;
        failure(): void;
    }
    type JobFunction = (this: JobThisType, ...args: any[]) => void;
    type JobFunctions = Record<string, JobFunction>;
    type RegisterFn = (jobFunctions: JobFunctions) => void;
    const jobs: JobFunctions;
    const collection: Mongo.Collection<JobDocument, JobDocument>;
    function configure(config: Partial<Config>): void;
    function register(newJobs: JobFunctions): void;
    function run(name: string, ...args: any): false | JobDocument;
    function execute(jobId: string): void;
    function replicate(jobId: string, config: Partial<JobConfig>): string;
    function reschedule(jobId: string, config: Partial<JobConfig>): void;
    function remove(jobId: string): boolean;
    function clear(state: '*' | JobStatus | JobStatus[], jobName: string, ...args: any[]): number;
    function findOne(jobName: string, ...args: any[]): JobDocument;
    function count(jobName: string, ...args: any[]): number;
    function countPending(jobName: string, ...args: any[]): number;
    const start: typeof Dominator.start;
    const stop: typeof Dominator.stop;
}
export {};
```

Appears to be more or less the same as written in the hand-written module. The only issue so-far is the lack of

```
declare module 'meteor/wildhart:jobs' {}
```

However, we should be able to re-export this to make things easy for developers.

**Comment by 67726e** [comment]
You'll either laugh here or think I'm insane, but there isn't (to my and or Google's knowledge) a way to simply re-export type definitions ... so I wrote a script to handle it:

```
#!/usr/bin/env bash

set -e

JOB_SOURCE="jobs.ts"
JOB_DEFINITION_SOURCE="jobs.d.ts"
MODULE_NAME="meteor/wildhart:jobs"

# Build w/
#   `jobs.ts`
#       `package.js` Irrelevant to Types...
#   `--skipLibCheck`
#   `--declaration`
#       We want the `jobs.d.ts` output...
#   `--emitDeclarationOnly`
#       We do not want the `jobs.js` output...
npx tsc \
    ${JOB_SOURCE} \
    --skipLibCheck \
    --declaration \
    --emitDeclarationOnly

# 1. Catenate Type Definition File
# 2. Prepend Tab per Line
    # See: https://unix.stackexchange.com/a/552704
TYPES=$(cat ./${JOB_DEFINITION_SOURCE} | ( TAB=$'\t' ; sed "s/^/$TAB/" ))

# Create Type Definition for Meteor Package Convention
echo "
declare module '${MODULE_NAME}' {
${TYPES}
}
" > test.d.ts
```

**Comment by 67726e** [comment]
This gives us a nice, clean file with matching indentation and all :)

```

declare module 'meteor/wildhart:jobs' {
	import { Mongo } from 'meteor/mongo';
	/********************************* Dominator *********************/
	declare namespace Dominator {
	    interface Document {
	        _id?: string;
	        serverId?: string;
	        pausedJobs: string[];
	        date?: Date;
	    }
	    export const collection: Mongo.Collection<Document, Document>;
	    export let lastPing: Readonly<Document>;
	    export function init(): void;
	    export function start(jobNames: string[] | string): void;
	    export function stop(jobNames: string[] | string): void;
	    export {};
	}
	/********************************* Public API *********************/
	export declare namespace Jobs {
	    interface Config {
	        startupDelay: number;
	        maxWait: number;
	        log: typeof console.log | boolean;
	        autoStart: boolean;
	        setServerId?: string | Function;
	        defaultCompletion?: 'success' | 'remove';
	    }
	    interface JobConfig {
	        in: any;
	        on: any;
	        priority: number;
	        date: Date;
	        state: string;
	        awaitAsync: boolean;
	        unique: boolean;
	        singular: boolean;
	        callback?: Function;
	    }
	    type JobStatus = "pending" | "success" | "failure" | "executing";
	    interface JobDocument {
	        _id: string;
	        name: string;
	        state: JobStatus;
	        arguments: any[];
	        due: Date;
	        priority: number;
	        created: Date;
	        awaitAsync?: boolean;
	    }
	    interface JobThisType {
	        document: JobDocument;
	        replicate(config: Partial<JobConfig>): string | null;
	        reschedule(config: Partial<JobConfig>): void;
	        remove(): boolean;
	        success(): void;
	        failure(): void;
	    }
	    type JobFunction = (this: JobThisType, ...args: any[]) => void;
	    type JobFunctions = Record<string, JobFunction>;
	    type RegisterFn = (jobFunctions: JobFunctions) => void;
	    const jobs: JobFunctions;
	    const collection: Mongo.Collection<JobDocument, JobDocument>;
	    function configure(config: Partial<Config>): void;
	    function register(newJobs: JobFunctions): void;
	    function run(name: string, ...args: any): false | JobDocument;
	    function execute(jobId: string): void;
	    function replicate(jobId: string, config: Partial<JobConfig>): string;
	    function reschedule(jobId: string, config: Partial<JobConfig>): void;
	    function remove(jobId: string): boolean;
	    function clear(state: '*' | JobStatus | JobStatus[], jobName: string, ...args: any[]): number;
	    function findOne(jobName: string, ...args: any[]): JobDocument;
	    function count(jobName: string, ...args: any[]): number;
	    function countPending(jobName: string, ...args: any[]): number;
	    const start: typeof Dominator.start;
	    const stop: typeof Dominator.stop;
	}
	export {};
}
```

**Comment by 67726e** [comment]
The only hiccup I'm having with the whole process here is that I'm not sure how to get the type definitions in an appropriate way, i.e. I would normally `meteor npm ci` in my Meteor application. However, this is a Meteor Package and such convention doesn't appear to work.

However, I have another hack to get around this fact...

1. Create a Throw-Away Meteor Application in `/tmp` with `meteor create --typescript stupid-hack-for-types`
2. Copy the `node_modules` for Type Definitions with `cp -a /tmp/stupid-hack-for-types/node_modules/ .`

If there is a proper way to get the types, I would rather use that so please let me know!

**Comment by 67726e** [comment]
The above build process now works, now just need to review the `README.md` vs. `jobs.d.ts` for deviations... Seeing as the code in the README works as described should be some simple changes, at least for an initial fix. Of note, I have had to add in a dozen or so `// @ts-ignore` statements in the code where the type definitions don't meet the reality of the code as happens with JS / TS.

**Comment by 67726e** [comment]
Also, found there is not an `Jobs.cancel` example in the README despite there being a link in the [`API Documentation`](https://github.com/wildhart/meteor.jobs#api-documentation).

**Comment by 67726e** [comment]
Found there is a `Jobs.get(...)` in the [`API Documentation`](https://github.com/wildhart/meteor.jobs#jobsget) that does not exist in-code.

**Comment by 67726e** [comment]
Manually copied over the resulting type definitions into my own application that prompted this ticket and definitions work.

**Comment by 67726e** [comment]
Alright, I may have gone a bit overboard here... but here is a pull request:

- Fix the Malformed Definitions per Original Issue
- Add Scripts for Building TypeScript Definitions
- Add Script for Testing TypeScript Definitions
- Fix `README.md` for Missing Methods in `Jobs`
- Add `DEVELOPMENT.md` for Scripts
