### ISSUE TITLE
Jobs are blocked when one is executing

### ISSUE THREAD

**Issue by sabativi** [wildhart/meteor.jobs#23]
I moved from msavin to this package yesterday : 

I have a job with the same name but different arguments, one failed this night and prevent the other from running.

I have the `singular: false` option, what should I do to prevent this ?

<img width="1101" alt="Screenshot 2023-05-16 at 09 16 02" src="https://github.com/wildhart/meteor.jobs/assets/2357779/5c5a0142-4121-423b-b85c-933e976ae6c4">

**Comment by chrismorison-wt** [comment]
@sabativi the job is still in `"executing"` status, so as far as this package concerned the job has not failed and so other jobs of that type will not get executed.  As per the docs:

> Each job must be resolved with success, failure, reschedule, and/or remove.
> See [Repeating Jobs](https://github.com/wildhart/meteor.jobs#repeating-jobs) and [Async Jobs/Promises](https://github.com/wildhart/meteor.jobs#async-jobs)

> Other jobs of the same type will still run when scheduled while asynchronous jobs are executing, unless the running job was configured with awaitSync: true, in which case the pending job will wait until the previous job of that name has completed.

Are you using the `awaitSync: true` option?  Are you resolving failed jobs with `this.failure()`?

Can you share the outline of the job code (including error handling), and also the code where the job is scheduled?

**Comment by sabativi** [comment]
Thanks @chrismorison-wt, no I am not using `awaitAsync`, I did not resolve failed jobs with `this.failure` I had it
