### ISSUE TITLE
Question regarding multi server env

### ISSUE THREAD

**Issue by sabativi** [wildhart/meteor.jobs#25]
Hello,

I have a question when running on multi server env ( I have three containers on galaxy ).

Only one server will be a worker ? Or can any server be a worker ?

Also, what happened in case where a new version is pushed to galaxy ?

I am asking those questions, because it seems that two jobs were run in parrallel which caused a problem in my app.

As I mentionned in #23 I am using `singular: false`, can also this be the problem ?

Thanks

**Comment by wildhart** [comment]
Hi @sabativi.  Only one server will be the 'worker' any any time.  But this could be any of your servers at random.

When the app starts up a server will take control of the queue by updating the `jobs_dominator_3` with the server id (which defaults to a random id) and the current time.  Other servers will see that another server is in control and ignore the job queue, unless they see that the 'worker' server hasn't pinged the `jobs_dominator_3` database in a while, in which case another server will take control.

When you deploy a new version to galaxy each server will restart, and in the default configuration will create a new server id. Each server will then watch the `jobs_dominator_3` database and eventually see that it hasn't been updated in a while.  Then one server will take control by putting its own server id in the database.

Please can you share your `Jobs.configure({...})` code?

**Comment by sabativi** [comment]
Hello,

Here is the config

```
Jobs.configure({
  startupDelay: 30000,
  defaultCompletion: 'success',
  log: Meteor.isDevelopment,
});
```

**Comment by wildhart** [comment]
That config looks good to me - I just wanted to check you weren't passing a static string to `setServerId` which would meant that all servers would think they're in control of the job queue.

Are you able to look at the server logs to confirm if the job was executed twice on the same server, or once on two servers?  Can you share the logs here?  You asked about a reboot - do you think this happened around the time of a reboot?

Are you able to reproduce this problem - i.e. the same job getting executed more than once?

**Comment by sabativi** [comment]
Hello,

I have tried to reproduce it but without any luck so I will close the issue.

Thanks
