### ISSUE TITLE
Handling async job fucntions

### ISSUE THREAD

**Issue by aliogaili** [wildhart/meteor.jobs#7]
Thanks, @wildhart for this efficient and easy to use jobs implementation.

I'm wondering how you handle jobs that return promises?

I seem to get the following error for async jobs:

`Jobs Job was not resolved with success, failure, reschedule or remove `

The action response can be delayed in the case of async jobs and this line [seems to throw](https://github.com/wildhart/meteor.jobs/blob/master/jobs.js#L391) the warning and assume the job failed, but it has not failed is just waiting for response. 

Perhaps we just add a state like "waiting" or "unresolved" instead of assuming failed. The state will get updated to "success" once `this.success()` is eventually called.

**Comment by wildhart** [comment]
That's a good suggestion, thanks @aliogaili, I'll look at adding that improvement.

In the mean time, if you immediately call this.success(), then run whatever async code you need to, then when they resolve or reject you can re-create the job if necessary.

**Comment by aliogaili** [comment]
Thanks yeah, I was thinking about doing that. It is a warning now, the only issue is the warning and the status reporting is incorrect, it first returns fail then a few seconds later it changes to success.  I just thought this would a minor change and it will have a clear support for async functions.

**Comment by wildhart** [comment]
Try upgrading to 1.0.10, and see the updated readme here: https://github.com/wildhart/meteor.jobs#async-jobs

**Comment by aliogaili** [comment]
Looks good @wildhart, makes the package more powerful.

 Is this published on Atmosphere?

**Comment by wildhart** [comment]
Yes it is: `meteor update wildhart:jobs`
